### ISSUE TITLE
Seeing values for Notification header, title, body

### ISSUE THREAD

**Issue by tonci77** [rdelrosario/xamarin-plugins#24]
I have one question, a little bit of struggle regarding PCL method:

 public class CrossPushNotificationListener : IPushNotificationListener
    {
        public void OnMessage (JObject values, DeviceType deviceType)
        {
            Debug.WriteLine ("Message Arrived");
        }  
        .......
I didn’t quite understood how to set (customize) “Notification” Title, Icon, Subject, Message text OnMessage event ?

Let’s say that receiving object values (JObject) contains strings/values for Notification Title, Subject, Message , so what would be the right aprouch in PCL project to applay these values before Notification is pop uped on user screen (both Android & iOs) ?

Thank's in advance for answer or suggestion.

**Comment by rdelrosario** [comment]
Hi

On the Android project you can set what keys on you MainActivity or
Application class to display on the notification:

```
//The sets the key associated with the value will be used to show the
title for the notification
public static string NotificationContentTitleKey { get; set; }

//The sets the key associated with the value will be used to show the
text for the notification
public static string NotificationContentTextKey { get; set; }

//The sets the key associated with the root value will be used to show
the text inside it for the notification
public static string NotificationContentDataKey { get; set; }

//The sets the resource id for the icon will be used for the notification
public static int IconResource { get; set; }

//The sets the sound  uri will be used for the notification
public static Android.Net.Uri SoundUri { get; set; }
```

The key you set for the NotificationContentTitleKey will be the one
displayed as the notification title. For example if you set key 'subject',
then will look for the value associated to this key to display as the title.

The key you set for the NotificationContentTextKey  will be the one
displayed as the notification title. For example if you set key 'message',
then will look for the value associated to this key to display as the
message.

You can set the icon by setting the IconResource property to the desired
drawable resource id.

On iOS is based as the Apple Standard since the Notifications values
displayed is managed automatically based on the APS notification message.

Let me know if you got any other questions. Hope this helps!

**Comment by rdelrosario** [comment]
Btw, this is set using CrossPushNotification.NotificationContentTitleKey =
"title" for example.

**Comment by tonci77** [comment]
Thank s a lot....
I guess that I wasn’t reading with full attention that read-me file :-)

![screen shot 2015-12-16 at 15 24 11](https://cloud.githubusercontent.com/assets/16320604/11843290/1d5eee9c-a409-11e5-9760-9e5d94ea9645.png)

![screen shot 2015-12-16 at 15 19 04](https://cloud.githubusercontent.com/assets/16320604/11843260/ed1a938a-a408-11e5-98bd-e6016c4863ee.png)

![screenshot_2015-12-16-15-20-55](https://cloud.githubusercontent.com/assets/16320604/11843270/fc3b1538-a408-11e5-9038-c764ea31545a.png)

**Comment by Ingenator** [comment]
Hi guys! i'm wondering if there's a way to style the notification.

Is there a property or something to set notifications style as: big text, inbox and image?

Thanks for your time and what a nice plugin @rdelrosario !! you rock!

**Comment by rdelrosario** [comment]
Could you show an example of what you would like to achieve?

**Comment by Ingenator** [comment]
The examples are [here](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/local_notifications_in_android/#Big_Text_Style) they are for Android, actually the notification is recieved but the text is not visible because of it's length and it can't be dragged down to see all of its conent.

It shown like this:
![FIRST](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/local_notifications_in_android/Images/15-big-text-notification.png)

And it could be converted to big text like this:
![Second](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/local_notifications_in_android/Images/16-big-text-expanded.png)

The other one is an inbox style:

![Third](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/local_notifications_in_android/Images/20-inbox-compact.png)

and when you drag it down is shown like this:

![fourth](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/local_notifications_in_android/Images/21-inbox-expanded.png)

Is there a way to achieve that?
Thanks again!

**Comment by rdelrosario** [comment]
Right no. there's no way using the plugin. But you could use other plugin to achieve this and turn off the show notifications in this plugin. But this surely looks like something we would like to add, so i will include this on the plugin whenever have some time.

**Comment by Ingenator** [comment]
Yeah that would be great! Looking forward for it! Thank you!
